import subprocess
import os
import sys

# This File is where the execution originates from
# It uses a terminal menu to select which renderer to use

def fetchRenderers(renderersPath):
    print(renderersPath)
    renderers = os.listdir(renderersPath)
    print(renderers)
    return renderers

def chooseRenderer():
    # TODO rewrite this as an interactable menu rather than input()
    # ! This function was generated by autofill
    renderersPath = __file__.replace("src.py", "renderers")
    renderers = fetchRenderers(renderersPath)
    print("Available Renderers:")
    for index, renderer in enumerate(renderers):
        print(f"{index + 1}. {renderer}")

    choice = int(input("Select a renderer by number: ")) - 1
    if 0 <= choice < len(renderers):
        selected_renderer = renderers[choice]
        print(f"You selected: {selected_renderer}")
        return str(renderersPath + "\\" + selected_renderer)
    else:
        print("Invalid selection. Please try again.")
        return chooseRenderer()
    # ! This function was generated by autofill

def startup():
    print("Welcome to PyChess")

    renderer = chooseRenderer()
    subprocess.run([sys.executable, renderer])

if __name__ == "__main__":
    startup()
