import os
import sys
sys.dont_write_bytecode = True 
import importlib.util
from ChessClasses import *
# This File is where the execution originates from
# It uses a terminal menu to select which renderer to use

def fetchRenderers(renderersPath):
    print(renderersPath)
    renderers = os.listdir(renderersPath)
    print(renderers)
    return renderers

def chooseRenderer():
    # TODO rewrite this as an interactable menu rather than input()
    # ! This function was generated by autofill
    renderersPath = __file__.replace("src.py", "renderers")
    renderers = fetchRenderers(renderersPath)
    print("Available Renderers:")
    for index, renderer in enumerate(renderers):
        print(f"{index + 1}. {renderer}")

    choice = int(input("Select a renderer by number: ")) - 1
    if 0 <= choice < len(renderers):
        selected_renderer = renderers[choice]
        print(f"You selected: {selected_renderer}")
        return selected_renderer
    else:
        print("Invalid selection. Please try again.")
        return chooseRenderer()
    # ! This function was generated by autofill

def startup():
    global  renderer
    print("Welcome to PyChess")

    renderers_path = __file__.replace("src.py", "renderers") + "\\" + chooseRenderer()
    # AI code
    # creates a ?spec?
    spec = importlib.util.spec_from_file_location("selected_renderer", renderers_path)

    # renderer is going to be the name of the object for the file that you can reference
    renderer = importlib.util.module_from_spec(spec)

    # equivalent of import but can take in file paths
    spec.loader.exec_module(renderer)
    # AI code

def gameloop():

    board = Board()
    board.boardSetup()
    renderer.draw(board)
    running = True

    while running:
        command = input("command: ")
        if command == "end":
            running = False
        # use format>  21 33  < in order to make moves
        elif len(command) == 5 and command[2] == " ":
            command = [int(command[0])-1,int(command[1])-1,int(command[3])-1,int(command[4])-1]
            print(board.squares[command[0]][command[1]].position.change([command[2], command[3]]))

        renderer.draw(board)


if __name__ == "__main__":
    startup()
    gameloop()
